name: DeathSwap
version: 1.2
api-version: 1.15
main: me.Cuble1234.deathswap.DeathSwap
author: Cuble1234

commands:
    ds:
        usage: /<command>
        description: start the DeathSwap
        
permission:
    deathswap.command.start:
       description: start the DeathSwap game
       default: true